
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var k={},n;for(n in e)e.hasOwnProperty(n)&&(k[n]=e[n]);var aa=[],ba="./this.program";function ca(a,b){throw b;}var da="object"===typeof window,r="function"===typeof importScripts,ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,u="",fa,ha,ia,v,w;
if(ea)u=r?require("path").dirname(u)+"/":__dirname+"/",fa=function(a,b){v||(v=require("fs"));w||(w=require("path"));a=w.normalize(a);return v.readFileSync(a,b?null:"utf8")},ia=function(a){a=fa(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},ha=function(a,b,c){v||(v=require("fs"));w||(w=require("path"));a=w.normalize(a);v.readFile(a,function(d,f){d?c(d):b(f.buffer)})},1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/")),aa=process.argv.slice(2),"undefined"!==typeof module&&
(module.exports=e),process.on("uncaughtException",function(a){if(!(a instanceof ja))throw a;}),process.on("unhandledRejection",x),ca=function(a,b){if(noExitRuntime||0<ka)throw process.exitCode=a,b;process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(da||r)r?u=self.location.href:"undefined"!==typeof document&&document.currentScript&&(u=document.currentScript.src),u=0!==u.indexOf("blob:")?u.substr(0,u.lastIndexOf("/")+1):"",fa=function(a){var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},r&&(ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var y=e.print||console.log.bind(console),z=e.printErr||console.warn.bind(console);for(n in k)k.hasOwnProperty(n)&&(e[n]=k[n]);
k=null;e.arguments&&(aa=e.arguments);e.thisProgram&&(ba=e.thisProgram);e.quit&&(ca=e.quit);function la(a){ma||(ma={});ma[a]||(ma[a]=1,z(a))}var ma,A;e.wasmBinary&&(A=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&x("no native wasm support detected");var na,B=!1,oa;function assert(a,b){a||x("Assertion failed: "+b)}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&pa)return pa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
function ra(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ta(a){var b=sa(a)+1,c=ua(b);ra(a,va,c,b);return c}var va,D,wa,E,xa,F,G,ya=[],za=[],Aa=[],Ba=[],Ca=[],ka=0;function Da(){var a=e.preRun.shift();ya.unshift(a)}var H=0,Ea=null,I=null;e.preloadedImages={};e.preloadedAudios={};
function x(a){if(e.onAbort)e.onAbort(a);z(a);B=!0;oa=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Fa(){return J.startsWith("data:application/octet-stream;base64,")}var J;J="test_shadows.wasm";if(!Fa()){var Ga=J;J=e.locateFile?e.locateFile(Ga,u):u+Ga}function Ha(){var a=J;try{if(a==J&&A)return new Uint8Array(A);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}
function Ia(){if(!A&&(da||r)){if("function"===typeof fetch&&!J.startsWith("file://"))return fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ha()});if(ha)return new Promise(function(a,b){ha(J,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ha()})}
function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.F;"number"===typeof c?void 0===b.i?G.get(c)():G.get(c)(b.i):c(void 0===b.i?null:b.i)}}}function Ka(a){a instanceof ja||"unwind"==a||(z("exception thrown: "+a),ca(1,a))}var La=[null,[],[]];
function Ma(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,h){b.drawElementsInstancedANGLE(c,d,f,g,h)})}
function Na(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Oa(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Pa=1,Qa=[],K=[],Ra=[],Sa=[],L=[],M=[],Ta=[],Ua={};function N(a){Va||(Va=a)}
function Wa(a){for(var b=Pa++,c=a.length;c<b;c++)a[c]=null;return b}function Xa(a,b){a.u||(a.u=a.getContext,a.getContext=function(d,f){f=a.u(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?Ya(c,b):0}function Ya(a,b){var c=Wa(Ta),d={P:c,attributes:b,version:b.I,o:a};a.canvas&&(a.canvas.L=d);Ta[c]=d;("undefined"===typeof b.D||b.D)&&Za(d);return c}
function Za(a){a||(a=$a);if(!a.H){a.H=!0;var b=a.o;Ma(b);Na(b);Oa(b);b.N=b.getExtension("EXT_disjoint_timer_query");b.T=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var ab={},Va,$a;function bb(a,b,c,d){for(var f=0;f<a;f++){var g=O[c](),h=g&&Wa(d);g?(g.name=h,d[h]=g):N(1282);E[b+4*f>>2]=h}}
function cb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=O.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":N(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:N(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)E[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){N(1280);z("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:N(1280);z("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}E[b>>2]=c}else N(1281)}function eb(a){var b=sa(a)+1,c=fb(b);ra(a,D,c,b);return c}
function gb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function P(a){var b=O.C;if(b){var c=b.h[a];"number"===typeof c&&(b.h[a]=c=O.getUniformLocation(b,b.A[a]+(0<c?"["+c+"]":"")));return c}N(1282)}var hb=[];
function ib(a,b){jb=a;kb=b;if(R)if(lb||(lb=!0),0==a)S=function(){var d=Math.max(0,mb+b-nb())|0;setTimeout(T,d)};else if(1==a)S=function(){ob(T)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);r?(void 0===e.setImmediates&&(e.setImmediates=[]),e.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}S=function(){setImmediate(T)}}}var nb;nb=ea?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};
function pb(a){function b(){if(c<qb){if(!(noExitRuntime||0<ka))try{rb(oa)}catch(d){Ka(d)}return!1}return!0}assert(!R,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");R=a;var c=qb;lb=!1;T=function(){if(!B)if(0<sb.length){var d=Date.now(),f=sb.shift();f.F(f.i);if(tb){var g=tb,h=0==g%1?g-1:Math.floor(g);tb=f.M?h:(8*g+(h+.5))/9}y('main loop blocker "'+f.name+'" took '+
(Date.now()-d)+" ms");e.setStatus&&(d=e.statusMessage||"Please wait...",f=tb,g=ub.O,f?f<g?e.setStatus(d+" ("+(g-f)+"/"+g+")"):e.setStatus(d):e.setStatus(""));b()&&setTimeout(T,0)}else b()&&(vb=vb+1|0,1==jb&&1<kb&&0!=vb%kb?S():(0==jb&&(mb=nb()),wb(a),b()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.J&&SDL.audio.J(),S())))}}function xb(a){if(!B)try{a()}catch(b){Ka(b)}}function yb(a,b){setTimeout(function(){xb(a)},b)}var lb=!1,S=null,qb=0,R=null,jb=0,kb=0,vb=0,sb=[];
function wb(a){B||e.preMainLoop&&!1===e.preMainLoop()||(xb(a),e.postMainLoop&&e.postMainLoop())}var ub={},mb,T,tb,U=!1,zb=!1,Ab=[];
function Bb(){function a(){zb=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!Cb){Cb=!0;try{Db=!0}catch(c){Db=!1,y("warning: no blob constructor, cannot create blobs with mimetypes")}Eb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Db?null:y("warning: no BlobBuilder");Fb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;e.v||"undefined"!==typeof Fb||(y("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.v=!0);e.preloadPlugins.push({canHandle:function(c){return!e.v&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,f,g){var h=null;if(Db)try{h=new Blob([c],{type:Gb(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Gb(d)}))}catch(p){la("Blob constructor present but fails: "+
p+"; falling back to blob builder")}h||(h=new Eb,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var l=Fb.createObjectURL(h),m=new Image;m.onload=function(){assert(m.complete,"Image "+d+" could not be decoded");var p=document.createElement("canvas");p.width=m.width;p.height=m.height;p.getContext("2d").drawImage(m,0,0);e.preloadedImages[d]=p;Fb.revokeObjectURL(l);f&&f(c)};m.onerror=function(){y("Image "+l+" could not be decoded");g&&g()};m.src=l}});e.preloadPlugins.push({canHandle:function(c){return!e.U&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,f,g){function h(q){m||(m=!0,e.preloadedAudios[d]=q,f&&f(c))}function l(){m||(m=!0,e.preloadedAudios[d]=new Audio,g&&g())}var m=!1;if(Db){try{var p=new Blob([c],{type:Gb(d)})}catch(q){return l()}p=Fb.createObjectURL(p);var t=new Audio;t.addEventListener("canplaythrough",function(){h(t)},!1);t.onerror=function(){if(!m){y("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var q="",C=0,Q=0,db=0;db<c.length;db++)for(C=
C<<8|c[db],Q+=8;6<=Q;){var qc=C>>Q-6&63;Q-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[qc]}2==Q?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(C&3)<<4],q+="=="):4==Q&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(C&15)<<2],q+="=");t.src="data:audio/x-"+d.substr(-3)+";base64,"+q;h(t)}};t.src=p;yb(function(){h(t)},1E4)}else return l()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&
b.addEventListener("click",function(c){!zb&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Hb(a,b,c,d){if(b&&e.g&&a==e.canvas)return e.g;var f;if(b){var g={antialias:!1,alpha:!1,I:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof ab&&(f=Xa(a,g)))var l=Ta[f].o}else l=a.getContext("2d");if(!l)return null;c&&(b||assert("undefined"===typeof O,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.g=l,b&&($a=Ta[f],e.g=O=$a&&$a.o),e.V=b,Ab.forEach(function(m){m()}),Bb());return l}var Ib=!1,Jb=void 0,V=void 0;
function Kb(a,b){function c(){U=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Lb,Jb&&d.requestPointerLock(),U=!0,V?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=xa[SDL.screen>>2]|8388608),Mb(e.canvas),Nb()):Mb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),V?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=xa[SDL.screen>>2]&-8388609),
Mb(e.canvas),Nb()):Mb(d));if(e.onFullScreen)e.onFullScreen(U);if(e.onFullscreen)e.onFullscreen(U)}Jb=a;V=b;"undefined"===typeof Jb&&(Jb=!0);"undefined"===typeof V&&(V=!1);var d=e.canvas;Ib||(Ib=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var f=document.createElement("div");d.parentNode.insertBefore(f,d);f.appendChild(d);f.requestFullscreen=
f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);f.requestFullscreen()}
function Lb(){if(!U)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Ob=0;function ob(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Ob)Ob=b+1E3/60;else for(;b+2>=Ob;)Ob+=1E3/60;setTimeout(a,Math.max(Ob-b,0))}}
function Gb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var W=0,X=0,Pb=0,Qb=0;
function Rb(a){if(zb)"mousemove"!=a.type&&"mozMovementX"in a?Pb=Qb=0:(Pb=a.movementX||a.mozMovementX||a.webkitMovementX||0,Qb=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(W=SDL.R+Pb,X=SDL.S+Qb):(W+=Pb,X+=Qb);else{var b=e.canvas.getBoundingClientRect(),c=e.canvas.width,d=e.canvas.height,f="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==a.type&&
"touchmove"!==a.type&&(f=a.pageX-(f+b.left),a=a.pageY-(g+b.top),f*=c/b.width,a*=d/b.height,Pb=f-W,Qb=a-X,W=f,X=a)}}var Sb=[];function Nb(){var a=e.canvas;Sb.forEach(function(b){b(a.width,a.height)})}function Tb(a,b,c){Mb(e.canvas,a,b);c||Nb()}
function Mb(a,b,c){b&&c?(a.K=b,a.G=c):(b=a.K,c=a.G);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*g)}V?
(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Cb,Db,Eb,Fb;
function Ub(){Vb&&!Wb&&(Wb=!0,ob(function(){Wb=!1;wb(function(){G.get(Vb)()})}))}var Xb=null,Yb=null,Vb=null,Zb=null,$b=null,ac=null,Y=null,bc=0,cc=256,dc=256,ec=18,Wb=!1;function fc(a){bc=0;a.shiftKey&&(bc+=1);a.ctrlKey&&(bc+=2);a.altKey&&(bc+=4)}function gc(a){Rb(a)}
function hc(a){if(a.ctrlKey||a.altKey||a.metaKey)return null;var b=a.keyCode;if(48<=b&&57>=b)return b;if(65<=b&&90>=b)return a.shiftKey?b:b+32;if(96<=b&&105>=b)return b-48;if(106<=b&&111>=b)return b-106+42;switch(b){case 9:case 13:case 27:case 32:case 61:return b}a=a.shiftKey;switch(b){case 186:return a?58:59;case 187:return a?43:61;case 188:return a?60:44;case 189:return a?95:45;case 190:return a?62:46;case 191:return a?63:47;case 219:return a?123:91;case 220:return a?124:47;case 221:return a?125:
93;case 222:return a?34:39}return null}
function ic(a){if($b||Zb){var b=null;switch(a.keyCode){case 8:b=120;break;case 46:b=111;break;case 112:b=1;break;case 113:b=2;break;case 114:b=3;break;case 115:b=4;break;case 116:b=5;break;case 117:b=6;break;case 118:b=7;break;case 119:b=8;break;case 120:b=9;break;case 121:b=10;break;case 122:b=11;break;case 123:b=12;break;case 37:b=100;break;case 38:b=101;break;case 39:b=102;break;case 40:b=103;break;case 33:b=104;break;case 34:b=105;break;case 36:b=106;break;case 35:b=107;break;case 45:b=108;break;
case 16:case 5:b=112;break;case 6:b=113;break;case 17:case 3:b=114;break;case 4:b=115;break;case 18:case 2:b=116;break;case 1:b=117}null!==b?$b&&(a.preventDefault(),fc(a),G.get($b)(b,W,X)):(b=hc(a),null!==b&&Zb&&(a.preventDefault(),fc(a),G.get(Zb)(b,W,X)))}}function jc(){}
function Z(a){if(a.target==e.canvas){var b=a.changedTouches[0];switch(a.type){case "touchstart":var c="mousedown";break;case "touchmove":c="mousemove";break;case "touchend":c="mouseup";break;default:return}var d=document.createEvent("MouseEvent");d.initMouseEvent(c,!0,!0,window,1,b.screenX,b.screenY,b.clientX,b.clientY,!1,!1,!1,!1,0,null);b.target.dispatchEvent(d);a.preventDefault()}}
function kc(a){Rb(a);if(a.target==e.canvas&&Y){try{a.target.setCapture()}catch(b){}a.preventDefault();fc(a);G.get(Y)(a.button,0,W,X)}}function lc(a){Rb(a);Y&&(a.preventDefault(),fc(a),G.get(Y)(a.button,1,W,X))}
function mc(a){Rb(a);switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);var c=3;0>b&&(c=4);Y&&(a.preventDefault(),fc(a),G.get(Y)(c,0,W,X))}
for(var O,nc=new Float32Array(288),oc=0;288>oc;++oc)hb[oc]=nc.subarray(0,oc+1);e.requestFullscreen=function(a,b){Kb(a,b)};e.requestAnimationFrame=function(a){ob(a)};e.setCanvasSize=function(a,b,c){Tb(a,b,c)};e.pauseMainLoop=function(){S=null;qb++};e.resumeMainLoop=function(){qb++;var a=jb,b=kb,c=R;R=null;pb(c);ib(a,b);S()};e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
e.createContext=function(a,b,c,d){return Hb(a,b,c,d)};
var pc={emscripten_memcpy_big:function(a,b,c){D.copyWithin(a,b,b+c)},emscripten_resize_heap:function(){x("OOM")},exit:function(a){rb(a)},fd_close:function(){return 0},fd_seek:function(){},fd_write:function(a,b,c,d){for(var f=0,g=0;g<c;g++){for(var h=E[b+8*g>>2],l=E[b+(8*g+4)>>2],m=0;m<l;m++){var p=D[h+m],t=La[a];0===p||10===p?((1===a?y:z)(qa(t,0)),t.length=0):t.push(p)}f+=l}E[d>>2]=f;return 0},glActiveTexture:function(a){O.activeTexture(a)},glAttachShader:function(a,b){O.attachShader(K[a],M[b])},
glBindBuffer:function(a,b){O.bindBuffer(a,Qa[b])},glBindFramebuffer:function(a,b){O.bindFramebuffer(a,Ra[b])},glBindRenderbuffer:function(a,b){O.bindRenderbuffer(a,Sa[b])},glBindTexture:function(a,b){O.bindTexture(a,L[b])},glBlendFunc:function(a,b){O.blendFunc(a,b)},glBufferData:function(a,b,c,d){O.bufferData(a,c?D.subarray(c,c+b):b,d)},glCheckFramebufferStatus:function(a){return O.checkFramebufferStatus(a)},glClear:function(a){O.clear(a)},glClearColor:function(a,b,c,d){O.clearColor(a,b,c,d)},glColorMask:function(a,
b,c,d){O.colorMask(!!a,!!b,!!c,!!d)},glCompileShader:function(a){O.compileShader(M[a])},glCreateProgram:function(){var a=Wa(K),b=O.createProgram();b.name=a;b.m=b.j=b.l=0;b.s=1;K[a]=b;return a},glCreateShader:function(a){var b=Wa(M);M[b]=O.createShader(a);return b},glCullFace:function(a){O.cullFace(a)},glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],f=Qa[d];f&&(O.deleteBuffer(f),f.name=0,Qa[d]=null)}},glDeleteProgram:function(a){if(a){var b=K[a];b?(O.deleteProgram(b),b.name=0,
K[a]=null):N(1281)}},glDeleteShader:function(a){if(a){var b=M[a];b?(O.deleteShader(b),M[a]=null):N(1281)}},glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],f=L[d];f&&(O.deleteTexture(f),f.name=0,L[d]=null)}},glDepthMask:function(a){O.depthMask(!!a)},glDisable:function(a){O.disable(a)},glDisableVertexAttribArray:function(a){O.disableVertexAttribArray(a)},glDrawArrays:function(a,b,c){O.drawArrays(a,b,c)},glDrawElements:function(a,b,c,d){O.drawElements(a,b,c,d)},glEnable:function(a){O.enable(a)},
glEnableVertexAttribArray:function(a){O.enableVertexAttribArray(a)},glFramebufferRenderbuffer:function(a,b,c,d){O.framebufferRenderbuffer(a,b,c,Sa[d])},glFramebufferTexture2D:function(a,b,c,d,f){O.framebufferTexture2D(a,b,c,L[d],f)},glFrontFace:function(a){O.frontFace(a)},glGenBuffers:function(a,b){bb(a,b,"createBuffer",Qa)},glGenFramebuffers:function(a,b){bb(a,b,"createFramebuffer",Ra)},glGenRenderbuffers:function(a,b){bb(a,b,"createRenderbuffer",Sa)},glGenTextures:function(a,b){bb(a,b,"createTexture",
L)},glGetAttribLocation:function(a,b){return O.getAttribLocation(K[a],b?qa(D,b,void 0):"")},glGetIntegerv:function(a,b){cb(a,b)},glGetProgramInfoLog:function(a,b,c,d){a=O.getProgramInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?ra(a,D,d,b):0;c&&(E[c>>2]=b)},glGetProgramiv:function(a,b,c){if(c)if(a>=Pa)N(1281);else if(a=K[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1;else if(35719==b){if(!a.m)for(b=0;b<O.getProgramParameter(a,35718);++b)a.m=Math.max(a.m,
O.getActiveUniform(a,b).name.length+1);E[c>>2]=a.m}else if(35722==b){if(!a.j)for(b=0;b<O.getProgramParameter(a,35721);++b)a.j=Math.max(a.j,O.getActiveAttrib(a,b).name.length+1);E[c>>2]=a.j}else if(35381==b){if(!a.l)for(b=0;b<O.getProgramParameter(a,35382);++b)a.l=Math.max(a.l,O.getActiveUniformBlockName(a,b).length+1);E[c>>2]=a.l}else E[c>>2]=O.getProgramParameter(a,b);else N(1281)},glGetShaderInfoLog:function(a,b,c,d){a=O.getShaderInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?ra(a,D,d,b):
0;c&&(E[c>>2]=b)},glGetShaderiv:function(a,b,c){c?35716==b?(a=O.getShaderInfoLog(M[a]),null===a&&(a="(unknown error)"),E[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(M[a]),E[c>>2]=a?a.length+1:0):E[c>>2]=O.getShaderParameter(M[a],b):N(1281)},glGetString:function(a){var b=Ua[a];if(!b){switch(a){case 7939:b=O.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=eb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=O.getParameter(a))||N(1280);b=b&&eb(b);break;
case 7938:b=eb("OpenGL ES 2.0 ("+O.getParameter(7938)+")");break;case 35724:b=O.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=eb(b);break;default:N(1280)}Ua[a]=b}return b},glGetUniformLocation:function(a,b){b=b?qa(D,b,void 0):"";if(a=K[a]){var c=a,d=c.h,f=c.B,g;if(!d)for(c.h=d={},c.A={},g=0;g<O.getProgramParameter(c,35718);++g){var h=O.getActiveUniform(c,g);var l=h.name;h=h.size;var m=
gb(l);m=0<m?l.slice(0,m):l;var p=c.s;c.s+=h;f[m]=[h,p];for(l=0;l<h;++l)d[p]=l,c.A[p++]=m}c=a.h;d=0;f=b;g=gb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,f=b.slice(0,g));if((f=a.B[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else N(1281);return-1},glLineWidth:function(a){O.lineWidth(a)},glLinkProgram:function(a){a=K[a];O.linkProgram(a);a.h=0;a.B={}},glPolygonOffset:function(a,b){O.polygonOffset(a,b)},glRenderbufferStorage:function(a,b,c,d){O.renderbufferStorage(a,b,c,d)},glShaderSource:function(a,
b,c,d){for(var f="",g=0;g<b;++g){var h=d?E[d+4*g>>2]:-1,l=E[c+4*g>>2];h=l?qa(D,l,0>h?void 0:h):"";f+=h}O.shaderSource(M[a],f)},glTexImage2D:function(a,b,c,d,f,g,h,l,m){var p=O,t=p.texImage2D;if(m){var q=l-5120;q=1==q?D:4==q?E:6==q?F:5==q||28922==q?xa:wa;var C=31-Math.clz32(q.BYTES_PER_ELEMENT);m=q.subarray(m>>C,m+f*(d*({5:3,6:4,8:2,29502:3,29504:4}[h-6402]||1)*(1<<C)+4-1&-4)>>C)}else m=null;t.call(p,a,b,c,d,f,g,h,l,m)},glTexParameterf:function(a,b,c){O.texParameterf(a,b,c)},glTexParameteri:function(a,
b,c){O.texParameteri(a,b,c)},glUniform1f:function(a,b){O.uniform1f(P(a),b)},glUniform1i:function(a,b){O.uniform1i(P(a),b)},glUniform2f:function(a,b,c){O.uniform2f(P(a),b,c)},glUniform3f:function(a,b,c,d){O.uniform3f(P(a),b,c,d)},glUniform3fv:function(a,b,c){if(96>=b)for(var d=hb[3*b-1],f=0;f<3*b;f+=3)d[f]=F[c+4*f>>2],d[f+1]=F[c+(4*f+4)>>2],d[f+2]=F[c+(4*f+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);O.uniform3fv(P(a),d)},glUniform4f:function(a,b,c,d,f){O.uniform4f(P(a),b,c,d,f)},glUniform4fv:function(a,
b,c){if(72>=b){var d=hb[4*b-1],f=F;c>>=2;for(var g=0;g<4*b;g+=4){var h=c+g;d[g]=f[h];d[g+1]=f[h+1];d[g+2]=f[h+2];d[g+3]=f[h+3]}}else d=F.subarray(c>>2,c+16*b>>2);O.uniform4fv(P(a),d)},glUniformMatrix4fv:function(a,b,c,d){if(18>=b){var f=hb[16*b-1],g=F;d>>=2;for(var h=0;h<16*b;h+=16){var l=d+h;f[h]=g[l];f[h+1]=g[l+1];f[h+2]=g[l+2];f[h+3]=g[l+3];f[h+4]=g[l+4];f[h+5]=g[l+5];f[h+6]=g[l+6];f[h+7]=g[l+7];f[h+8]=g[l+8];f[h+9]=g[l+9];f[h+10]=g[l+10];f[h+11]=g[l+11];f[h+12]=g[l+12];f[h+13]=g[l+13];f[h+14]=
g[l+14];f[h+15]=g[l+15]}}else f=F.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(P(a),!!c,f)},glUseProgram:function(a){a=K[a];O.useProgram(a);O.C=a},glVertexAttribPointer:function(a,b,c,d,f,g){O.vertexAttribPointer(a,b,c,!!d,f,g)},glViewport:function(a,b,c,d){O.viewport(a,b,c,d)},glutCreateWindow:function(){e.g=Hb(e.canvas,!0,!0,{antialias:0!=(ec&128),depth:0!=(ec&16),stencil:0!=(ec&32),alpha:0!=(ec&8)});return e.g?1:0},glutDestroyWindow:function(){e.g=void 0;return 1},glutDisplayFunc:function(a){Vb=
a},glutGet:function(a){switch(a){case 100:return 0;case 101:return 0;case 102:return e.canvas.width;case 103:return e.canvas.height;case 200:return e.canvas.width;case 201:return e.canvas.height;case 500:return 0;case 501:return 0;case 502:return cc;case 503:return dc;case 700:return Date.now()-Xb;case 105:return e.g.getContextAttributes().stencil?8:0;case 106:return e.g.getContextAttributes().depth?8:0;case 110:return e.g.getContextAttributes().alpha?8:0;case 120:return e.g.getContextAttributes().antialias?
1:0;default:throw"glutGet("+a+") not implemented yet";}},glutGetModifiers:function(){return bc},glutIdleFunc:function(a){function b(){Yb&&(G.get(Yb)(),yb(b,4))}Yb||yb(b,0);Yb=a},glutInit:function(){Xb=Date.now();var a="ontouchstart"in document.documentElement;a&&(window.addEventListener("touchmove",Z,!0),window.addEventListener("touchstart",Z,!0),window.addEventListener("touchend",Z,!0));window.addEventListener("keydown",ic,!0);window.addEventListener("keyup",jc,!0);window.addEventListener("mousemove",
gc,!0);window.addEventListener("mousedown",kc,!0);window.addEventListener("mouseup",lc,!0);window.addEventListener("mousewheel",mc,!0);window.addEventListener("DOMMouseScroll",mc,!0);Sb.push(function(b,c){ac&&G.get(ac)(b,c)});Ba.push(function(){a&&(window.removeEventListener("touchmove",Z,!0),window.removeEventListener("touchstart",Z,!0),window.removeEventListener("touchend",Z,!0));window.removeEventListener("keydown",ic,!0);window.removeEventListener("keyup",jc,!0);window.removeEventListener("mousemove",
gc,!0);window.removeEventListener("mousedown",kc,!0);window.removeEventListener("mouseup",lc,!0);window.removeEventListener("mousewheel",mc,!0);window.removeEventListener("DOMMouseScroll",mc,!0);e.canvas.width=e.canvas.height=1})},glutInitDisplayMode:function(a){ec=a},glutInitWindowPosition:function(){},glutInitWindowSize:function(a,b){Tb(cc=a,dc=b)},glutKeyboardFunc:function(a){Zb=a},glutMainLoop:function(){var a=e.canvas.width,b=e.canvas.height;Lb();Tb(a,b,!0);ac&&G.get(ac)(a,b);Ub();Ub();throw"unwind";
},glutMouseFunc:function(a){Y=a},glutPostRedisplay:Ub,glutReshapeFunc:function(a){ac=a},glutSpecialFunc:function(a){$b=a},glutSwapBuffers:function(){},setTempRet0:function(){}};
(function(){function a(f){e.asm=f.exports;na=e.asm.memory;f=na.buffer;e.HEAP8=va=new Int8Array(f);e.HEAP16=new Int16Array(f);e.HEAP32=E=new Int32Array(f);e.HEAPU8=D=new Uint8Array(f);e.HEAPU16=wa=new Uint16Array(f);e.HEAPU32=xa=new Uint32Array(f);e.HEAPF32=F=new Float32Array(f);e.HEAPF64=new Float64Array(f);G=e.asm.__indirect_function_table;za.unshift(e.asm.__wasm_call_ctors);H--;e.monitorRunDependencies&&e.monitorRunDependencies(H);0==H&&(null!==Ea&&(clearInterval(Ea),Ea=null),I&&(f=I,I=null,f()))}
function b(f){a(f.instance)}function c(f){return Ia().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(f,function(g){z("failed to asynchronously prepare wasm: "+g);x(g)})}var d={env:pc,wasi_snapshot_preview1:pc};H++;e.monitorRunDependencies&&e.monitorRunDependencies(H);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return z("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return A||"function"!==typeof WebAssembly.instantiateStreaming||
Fa()||J.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){z("wasm streaming compile failed: "+g);z("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.__wasm_call_ctors).apply(null,arguments)};var fb=e._malloc=function(){return(fb=e._malloc=e.asm.malloc).apply(null,arguments)};
e._main=function(){return(e._main=e.asm.main).apply(null,arguments)};e.___errno_location=function(){return(e.___errno_location=e.asm.__errno_location).apply(null,arguments)};e.stackSave=function(){return(e.stackSave=e.asm.stackSave).apply(null,arguments)};e.stackRestore=function(){return(e.stackRestore=e.asm.stackRestore).apply(null,arguments)};var ua=e.stackAlloc=function(){return(ua=e.stackAlloc=e.asm.stackAlloc).apply(null,arguments)};
e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.dynCall_jiji).apply(null,arguments)};var rc;function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}I=function sc(){rc||tc();rc||(I=sc)};
function tc(a){function b(){if(!rc&&(rc=!0,e.calledRun=!0,!B)){Ja(za);Ja(Aa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(uc){var c=a,d=e._main;c=c||[];var f=c.length+1,g=ua(4*(f+1));E[g>>2]=ta(ba);for(var h=1;h<f;h++)E[(g>>2)+h]=ta(c[h-1]);E[(g>>2)+f]=0;try{var l=d(f,g);rb(l)}catch(m){Ka(m)}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),Ca.unshift(c);Ja(Ca)}}a=a||aa;if(!(0<H)){if(e.preRun)for("function"==typeof e.preRun&&
(e.preRun=[e.preRun]);e.preRun.length;)Da();Ja(ya);0<H||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=tc;function rb(a){oa=oa=a;if(!(noExitRuntime||0<ka)){if(e.onExit)e.onExit(a);B=!0}ca(a,new ja(a))}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var uc=!0;e.noInitialRun&&(uc=!1);tc();
