
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var k={},n;for(n in e)e.hasOwnProperty(n)&&(k[n]=e[n]);var aa=[],ba="./this.program";function ca(a,b){throw b;}var da="object"===typeof window,r="function"===typeof importScripts,ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,u="",fa,ha,ia,v,w;
if(ea)u=r?require("path").dirname(u)+"/":__dirname+"/",fa=function(a,b){v||(v=require("fs"));w||(w=require("path"));a=w.normalize(a);return v.readFileSync(a,b?null:"utf8")},ia=function(a){a=fa(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},ha=function(a,b,c){v||(v=require("fs"));w||(w=require("path"));a=w.normalize(a);v.readFile(a,function(d,f){d?c(d):b(f.buffer)})},1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/")),aa=process.argv.slice(2),"undefined"!==typeof module&&
(module.exports=e),process.on("uncaughtException",function(a){if(!(a instanceof ja))throw a;}),process.on("unhandledRejection",x),ca=function(a,b){if(noExitRuntime||0<ka)throw process.exitCode=a,b;process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(da||r)r?u=self.location.href:"undefined"!==typeof document&&document.currentScript&&(u=document.currentScript.src),u=0!==u.indexOf("blob:")?u.substr(0,u.lastIndexOf("/")+1):"",fa=function(a){var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},r&&(ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var y=e.print||console.log.bind(console),z=e.printErr||console.warn.bind(console);for(n in k)k.hasOwnProperty(n)&&(e[n]=k[n]);
k=null;e.arguments&&(aa=e.arguments);e.thisProgram&&(ba=e.thisProgram);e.quit&&(ca=e.quit);function la(a){ma||(ma={});ma[a]||(ma[a]=1,z(a))}var ma,A;e.wasmBinary&&(A=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&x("no native wasm support detected");var na,C=!1,oa;function assert(a,b){a||x("Assertion failed: "+b)}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&pa)return pa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function D(a,b){return a?qa(E,a,b):""}
function ra(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ta(a){var b=sa(a)+1,c=ua(b);ra(a,va,c,b);return c}var va,E,wa,F,xa,G,H,ya=[],za=[],Aa=[],Ba=[],Ca=[],ka=0;function Da(){var a=e.preRun.shift();ya.unshift(a)}var I=0,Ea=null,J=null;e.preloadedImages={};e.preloadedAudios={};
function x(a){if(e.onAbort)e.onAbort(a);z(a);C=!0;oa=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Fa(){return K.startsWith("data:application/octet-stream;base64,")}var K;K="test_sdf.wasm";if(!Fa()){var Ga=K;K=e.locateFile?e.locateFile(Ga,u):u+Ga}function Ha(){var a=K;try{if(a==K&&A)return new Uint8Array(A);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}
function Ia(){if(!A&&(da||r)){if("function"===typeof fetch&&!K.startsWith("file://"))return fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Ha()});if(ha)return new Promise(function(a,b){ha(K,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ha()})}
function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.F;"number"===typeof c?void 0===b.i?H.get(c)():H.get(c)(b.i):c(void 0===b.i?null:b.i)}}}function Ka(a){a instanceof ja||"unwind"==a||(z("exception thrown: "+a),ca(1,a))}var La=[null,[],[]];
function Ma(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,h){b.drawElementsInstancedANGLE(c,d,f,g,h)})}
function Na(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Oa(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Pa=1,Qa=[],L=[],Ra=[],M=[],Sa=[],Ta={};function N(a){Ua||(Ua=a)}
function Va(a){for(var b=Pa++,c=a.length;c<b;c++)a[c]=null;return b}function Wa(a,b){a.u||(a.u=a.getContext,a.getContext=function(d,f){f=a.u(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?Xa(c,b):0}function Xa(a,b){var c=Va(Sa),d={P:c,attributes:b,version:b.I,o:a};a.canvas&&(a.canvas.L=d);Sa[c]=d;("undefined"===typeof b.D||b.D)&&Ya(d);return c}
function Ya(a){a||(a=Za);if(!a.H){a.H=!0;var b=a.o;Ma(b);Na(b);Oa(b);b.N=b.getExtension("EXT_disjoint_timer_query");b.T=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var $a={},Ua,Za;function ab(a,b,c,d){for(var f=0;f<a;f++){var g=O[c](),h=g&&Va(d);g?(g.name=h,d[h]=g):N(1282);F[b+4*f>>2]=h}}function cb(a){var b=sa(a)+1,c=db(b);ra(a,E,c,b);return c}
function eb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function P(a){var b=O.C;if(b){var c=b.h[a];"number"===typeof c&&(b.h[a]=c=O.getUniformLocation(b,b.A[a]+(0<c?"["+c+"]":"")));return c}N(1282)}var fb=[];
function gb(a,b){hb=a;ib=b;if(Q)if(jb||(jb=!0),0==a)S=function(){var d=Math.max(0,kb+b-lb())|0;setTimeout(T,d)};else if(1==a)S=function(){mb(T)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);r?(void 0===e.setImmediates&&(e.setImmediates=[]),e.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}S=function(){setImmediate(T)}}}var lb;lb=ea?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};
function nb(a){function b(){if(c<ob){if(!(noExitRuntime||0<ka))try{pb(oa)}catch(d){Ka(d)}return!1}return!0}assert(!Q,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Q=a;var c=ob;jb=!1;T=function(){if(!C)if(0<qb.length){var d=Date.now(),f=qb.shift();f.F(f.i);if(rb){var g=rb,h=0==g%1?g-1:Math.floor(g);rb=f.M?h:(8*g+(h+.5))/9}y('main loop blocker "'+f.name+'" took '+
(Date.now()-d)+" ms");e.setStatus&&(d=e.statusMessage||"Please wait...",f=rb,g=sb.O,f?f<g?e.setStatus(d+" ("+(g-f)+"/"+g+")"):e.setStatus(d):e.setStatus(""));b()&&setTimeout(T,0)}else b()&&(tb=tb+1|0,1==hb&&1<ib&&0!=tb%ib?S():(0==hb&&(kb=lb()),ub(a),b()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.J&&SDL.audio.J(),S())))}}function vb(a){if(!C)try{a()}catch(b){Ka(b)}}function wb(a,b){setTimeout(function(){vb(a)},b)}var jb=!1,S=null,ob=0,Q=null,hb=0,ib=0,tb=0,qb=[];
function ub(a){C||e.preMainLoop&&!1===e.preMainLoop()||(vb(a),e.postMainLoop&&e.postMainLoop())}var sb={},kb,T,rb,U=!1,xb=!1,yb=[];
function zb(){function a(){xb=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!Ab){Ab=!0;try{Bb=!0}catch(c){Bb=!1,y("warning: no blob constructor, cannot create blobs with mimetypes")}Cb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Bb?null:y("warning: no BlobBuilder");Db="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;e.v||"undefined"!==typeof Db||(y("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.v=!0);e.preloadPlugins.push({canHandle:function(c){return!e.v&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,f,g){var h=null;if(Bb)try{h=new Blob([c],{type:Eb(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Eb(d)}))}catch(p){la("Blob constructor present but fails: "+
p+"; falling back to blob builder")}h||(h=new Cb,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var l=Db.createObjectURL(h),m=new Image;m.onload=function(){assert(m.complete,"Image "+d+" could not be decoded");var p=document.createElement("canvas");p.width=m.width;p.height=m.height;p.getContext("2d").drawImage(m,0,0);e.preloadedImages[d]=p;Db.revokeObjectURL(l);f&&f(c)};m.onerror=function(){y("Image "+l+" could not be decoded");g&&g()};m.src=l}});e.preloadPlugins.push({canHandle:function(c){return!e.U&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,f,g){function h(q){m||(m=!0,e.preloadedAudios[d]=q,f&&f(c))}function l(){m||(m=!0,e.preloadedAudios[d]=new Audio,g&&g())}var m=!1;if(Bb){try{var p=new Blob([c],{type:Eb(d)})}catch(q){return l()}p=Db.createObjectURL(p);var t=new Audio;t.addEventListener("canplaythrough",function(){h(t)},!1);t.onerror=function(){if(!m){y("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var q="",B=0,R=0,bb=0;bb<c.length;bb++)for(B=
B<<8|c[bb],R+=8;6<=R;){var oc=B>>R-6&63;R-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[oc]}2==R?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(B&3)<<4],q+="=="):4==R&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(B&15)<<2],q+="=");t.src="data:audio/x-"+d.substr(-3)+";base64,"+q;h(t)}};t.src=p;wb(function(){h(t)},1E4)}else return l()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&
b.addEventListener("click",function(c){!xb&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Fb(a,b,c,d){if(b&&e.g&&a==e.canvas)return e.g;var f;if(b){var g={antialias:!1,alpha:!1,I:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof $a&&(f=Wa(a,g)))var l=Sa[f].o}else l=a.getContext("2d");if(!l)return null;c&&(b||assert("undefined"===typeof O,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.g=l,b&&(Za=Sa[f],e.g=O=Za&&Za.o),e.V=b,yb.forEach(function(m){m()}),zb());return l}var Gb=!1,Hb=void 0,V=void 0;
function Ib(a,b){function c(){U=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Jb,Hb&&d.requestPointerLock(),U=!0,V?("undefined"!=typeof SDL&&(F[SDL.screen>>2]=xa[SDL.screen>>2]|8388608),Kb(e.canvas),Lb()):Kb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),V?("undefined"!=typeof SDL&&(F[SDL.screen>>2]=xa[SDL.screen>>2]&-8388609),
Kb(e.canvas),Lb()):Kb(d));if(e.onFullScreen)e.onFullScreen(U);if(e.onFullscreen)e.onFullscreen(U)}Hb=a;V=b;"undefined"===typeof Hb&&(Hb=!0);"undefined"===typeof V&&(V=!1);var d=e.canvas;Gb||(Gb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var f=document.createElement("div");d.parentNode.insertBefore(f,d);f.appendChild(d);f.requestFullscreen=
f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);f.requestFullscreen()}
function Jb(){if(!U)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Mb=0;function mb(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Mb)Mb=b+1E3/60;else for(;b+2>=Mb;)Mb+=1E3/60;setTimeout(a,Math.max(Mb-b,0))}}
function Eb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var W=0,X=0,Nb=0,Ob=0;
function Pb(a){if(xb)"mousemove"!=a.type&&"mozMovementX"in a?Nb=Ob=0:(Nb=a.movementX||a.mozMovementX||a.webkitMovementX||0,Ob=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(W=SDL.R+Nb,X=SDL.S+Ob):(W+=Nb,X+=Ob);else{var b=e.canvas.getBoundingClientRect(),c=e.canvas.width,d=e.canvas.height,f="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==a.type&&
"touchmove"!==a.type&&(f=a.pageX-(f+b.left),a=a.pageY-(g+b.top),f*=c/b.width,a*=d/b.height,Nb=f-W,Ob=a-X,W=f,X=a)}}var Qb=[];function Lb(){var a=e.canvas;Qb.forEach(function(b){b(a.width,a.height)})}function Rb(a,b,c){Kb(e.canvas,a,b);c||Lb()}
function Kb(a,b,c){b&&c?(a.K=b,a.G=c):(b=a.K,c=a.G);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*g)}V?
(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Ab,Bb,Cb,Db;
function Sb(){Tb&&!Ub&&(Ub=!0,mb(function(){Ub=!1;ub(function(){H.get(Tb)()})}))}var Vb=null,Wb=null,Tb=null,Xb=null,Yb=null,Zb=null,Y=null,$b=0,ac=256,bc=256,cc=18,Ub=!1;function dc(a){$b=0;a.shiftKey&&($b+=1);a.ctrlKey&&($b+=2);a.altKey&&($b+=4)}function ec(a){Pb(a)}
function fc(a){if(a.ctrlKey||a.altKey||a.metaKey)return null;var b=a.keyCode;if(48<=b&&57>=b)return b;if(65<=b&&90>=b)return a.shiftKey?b:b+32;if(96<=b&&105>=b)return b-48;if(106<=b&&111>=b)return b-106+42;switch(b){case 9:case 13:case 27:case 32:case 61:return b}a=a.shiftKey;switch(b){case 186:return a?58:59;case 187:return a?43:61;case 188:return a?60:44;case 189:return a?95:45;case 190:return a?62:46;case 191:return a?63:47;case 219:return a?123:91;case 220:return a?124:47;case 221:return a?125:
93;case 222:return a?34:39}return null}
function gc(a){if(Yb||Xb){var b=null;switch(a.keyCode){case 8:b=120;break;case 46:b=111;break;case 112:b=1;break;case 113:b=2;break;case 114:b=3;break;case 115:b=4;break;case 116:b=5;break;case 117:b=6;break;case 118:b=7;break;case 119:b=8;break;case 120:b=9;break;case 121:b=10;break;case 122:b=11;break;case 123:b=12;break;case 37:b=100;break;case 38:b=101;break;case 39:b=102;break;case 40:b=103;break;case 33:b=104;break;case 34:b=105;break;case 36:b=106;break;case 35:b=107;break;case 45:b=108;break;
case 16:case 5:b=112;break;case 6:b=113;break;case 17:case 3:b=114;break;case 4:b=115;break;case 18:case 2:b=116;break;case 1:b=117}null!==b?Yb&&(a.preventDefault(),dc(a),H.get(Yb)(b,W,X)):(b=fc(a),null!==b&&Xb&&(a.preventDefault(),dc(a),H.get(Xb)(b,W,X)))}}function hc(){}
function Z(a){if(a.target==e.canvas){var b=a.changedTouches[0];switch(a.type){case "touchstart":var c="mousedown";break;case "touchmove":c="mousemove";break;case "touchend":c="mouseup";break;default:return}var d=document.createEvent("MouseEvent");d.initMouseEvent(c,!0,!0,window,1,b.screenX,b.screenY,b.clientX,b.clientY,!1,!1,!1,!1,0,null);b.target.dispatchEvent(d);a.preventDefault()}}
function ic(a){Pb(a);if(a.target==e.canvas&&Y){try{a.target.setCapture()}catch(b){}a.preventDefault();dc(a);H.get(Y)(a.button,0,W,X)}}function jc(a){Pb(a);Y&&(a.preventDefault(),dc(a),H.get(Y)(a.button,1,W,X))}
function kc(a){Pb(a);switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);var c=3;0>b&&(c=4);Y&&(a.preventDefault(),dc(a),H.get(Y)(c,0,W,X))}
for(var O,lc=new Float32Array(288),mc=0;288>mc;++mc)fb[mc]=lc.subarray(0,mc+1);e.requestFullscreen=function(a,b){Ib(a,b)};e.requestAnimationFrame=function(a){mb(a)};e.setCanvasSize=function(a,b,c){Rb(a,b,c)};e.pauseMainLoop=function(){S=null;ob++};e.resumeMainLoop=function(){ob++;var a=hb,b=ib,c=Q;Q=null;nb(c);gb(a,b);S()};e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
e.createContext=function(a,b,c,d){return Fb(a,b,c,d)};
var nc={__assert_fail:function(a,b,c,d){x("Assertion failed: "+D(a)+", at: "+[b?D(b):"unknown filename",c,d?D(d):"unknown function"])},__cxa_atexit:function(){},emscripten_memcpy_big:function(a,b,c){E.copyWithin(a,b,b+c)},emscripten_resize_heap:function(){x("OOM")},exit:function(a){pb(a)},fd_close:function(){return 0},fd_seek:function(){},fd_write:function(a,b,c,d){for(var f=0,g=0;g<c;g++){for(var h=F[b+8*g>>2],l=F[b+(8*g+4)>>2],m=0;m<l;m++){var p=E[h+m],t=La[a];0===p||10===p?((1===a?y:z)(qa(t,0)),
t.length=0):t.push(p)}f+=l}F[d>>2]=f;return 0},glActiveTexture:function(a){O.activeTexture(a)},glAttachShader:function(a,b){O.attachShader(L[a],M[b])},glBindAttribLocation:function(a,b,c){O.bindAttribLocation(L[a],b,D(c))},glBindBuffer:function(a,b){O.bindBuffer(a,Qa[b])},glBindTexture:function(a,b){O.bindTexture(a,Ra[b])},glBlendFunc:function(a,b){O.blendFunc(a,b)},glBufferData:function(a,b,c,d){O.bufferData(a,c?E.subarray(c,c+b):b,d)},glBufferSubData:function(a,b,c,d){O.bufferSubData(a,b,E.subarray(d,
d+c))},glClear:function(a){O.clear(a)},glClearColor:function(a,b,c,d){O.clearColor(a,b,c,d)},glCompileShader:function(a){O.compileShader(M[a])},glCreateProgram:function(){var a=Va(L),b=O.createProgram();b.name=a;b.m=b.j=b.l=0;b.s=1;L[a]=b;return a},glCreateShader:function(a){var b=Va(M);M[b]=O.createShader(a);return b},glCullFace:function(a){O.cullFace(a)},glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],f=Qa[d];f&&(O.deleteBuffer(f),f.name=0,Qa[d]=null)}},glDeleteProgram:function(a){if(a){var b=
L[a];b?(O.deleteProgram(b),b.name=0,L[a]=null):N(1281)}},glDeleteShader:function(a){if(a){var b=M[a];b?(O.deleteShader(b),M[a]=null):N(1281)}},glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],f=Ra[d];f&&(O.deleteTexture(f),f.name=0,Ra[d]=null)}},glDetachShader:function(a,b){O.detachShader(L[a],M[b])},glDisable:function(a){O.disable(a)},glDisableVertexAttribArray:function(a){O.disableVertexAttribArray(a)},glDrawArrays:function(a,b,c){O.drawArrays(a,b,c)},glDrawElements:function(a,
b,c,d){O.drawElements(a,b,c,d)},glEnable:function(a){O.enable(a)},glEnableVertexAttribArray:function(a){O.enableVertexAttribArray(a)},glFrontFace:function(a){O.frontFace(a)},glGenBuffers:function(a,b){ab(a,b,"createBuffer",Qa)},glGenTextures:function(a,b){ab(a,b,"createTexture",Ra)},glGetAttribLocation:function(a,b){return O.getAttribLocation(L[a],D(b))},glGetProgramInfoLog:function(a,b,c,d){a=O.getProgramInfoLog(L[a]);null===a&&(a="(unknown error)");b=0<b&&d?ra(a,E,d,b):0;c&&(F[c>>2]=b)},glGetProgramiv:function(a,
b,c){if(c)if(a>=Pa)N(1281);else if(a=L[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),F[c>>2]=a.length+1;else if(35719==b){if(!a.m)for(b=0;b<O.getProgramParameter(a,35718);++b)a.m=Math.max(a.m,O.getActiveUniform(a,b).name.length+1);F[c>>2]=a.m}else if(35722==b){if(!a.j)for(b=0;b<O.getProgramParameter(a,35721);++b)a.j=Math.max(a.j,O.getActiveAttrib(a,b).name.length+1);F[c>>2]=a.j}else if(35381==b){if(!a.l)for(b=0;b<O.getProgramParameter(a,35382);++b)a.l=Math.max(a.l,O.getActiveUniformBlockName(a,
b).length+1);F[c>>2]=a.l}else F[c>>2]=O.getProgramParameter(a,b);else N(1281)},glGetShaderInfoLog:function(a,b,c,d){a=O.getShaderInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?ra(a,E,d,b):0;c&&(F[c>>2]=b)},glGetShaderiv:function(a,b,c){c?35716==b?(a=O.getShaderInfoLog(M[a]),null===a&&(a="(unknown error)"),F[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(M[a]),F[c>>2]=a?a.length+1:0):F[c>>2]=O.getShaderParameter(M[a],b):N(1281)},glGetString:function(a){var b=Ta[a];if(!b){switch(a){case 7939:b=
O.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=cb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=O.getParameter(a))||N(1280);b=b&&cb(b);break;case 7938:b=cb("OpenGL ES 2.0 ("+O.getParameter(7938)+")");break;case 35724:b=O.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=cb(b);break;default:N(1280)}Ta[a]=b}return b},glGetUniformLocation:function(a,
b){b=D(b);if(a=L[a]){var c=a,d=c.h,f=c.B,g;if(!d)for(c.h=d={},c.A={},g=0;g<O.getProgramParameter(c,35718);++g){var h=O.getActiveUniform(c,g);var l=h.name;h=h.size;var m=eb(l);m=0<m?l.slice(0,m):l;var p=c.s;c.s+=h;f[m]=[h,p];for(l=0;l<h;++l)d[p]=l,c.A[p++]=m}c=a.h;d=0;f=b;g=eb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,f=b.slice(0,g));if((f=a.B[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else N(1281);return-1},glLinkProgram:function(a){a=L[a];O.linkProgram(a);a.h=0;a.B={}},glPolygonOffset:function(a,
b){O.polygonOffset(a,b)},glScissor:function(a,b,c,d){O.scissor(a,b,c,d)},glShaderSource:function(a,b,c,d){for(var f="",g=0;g<b;++g){var h=d?F[d+4*g>>2]:-1;f+=D(F[c+4*g>>2],0>h?void 0:h)}O.shaderSource(M[a],f)},glTexImage2D:function(a,b,c,d,f,g,h,l,m){var p=O,t=p.texImage2D;if(m){var q=l-5120;q=1==q?E:4==q?F:6==q?G:5==q||28922==q?xa:wa;var B=31-Math.clz32(q.BYTES_PER_ELEMENT);m=q.subarray(m>>B,m+f*(d*({5:3,6:4,8:2,29502:3,29504:4}[h-6402]||1)*(1<<B)+4-1&-4)>>B)}else m=null;t.call(p,a,b,c,d,f,g,h,l,
m)},glTexParameteri:function(a,b,c){O.texParameteri(a,b,c)},glUniform1i:function(a,b){O.uniform1i(P(a),b)},glUniform2f:function(a,b,c){O.uniform2f(P(a),b,c)},glUniform3f:function(a,b,c,d){O.uniform3f(P(a),b,c,d)},glUniform3fv:function(a,b,c){if(96>=b)for(var d=fb[3*b-1],f=0;f<3*b;f+=3)d[f]=G[c+4*f>>2],d[f+1]=G[c+(4*f+4)>>2],d[f+2]=G[c+(4*f+8)>>2];else d=G.subarray(c>>2,c+12*b>>2);O.uniform3fv(P(a),d)},glUniform4f:function(a,b,c,d,f){O.uniform4f(P(a),b,c,d,f)},glUniform4fv:function(a,b,c){if(72>=b){var d=
fb[4*b-1],f=G;c>>=2;for(var g=0;g<4*b;g+=4){var h=c+g;d[g]=f[h];d[g+1]=f[h+1];d[g+2]=f[h+2];d[g+3]=f[h+3]}}else d=G.subarray(c>>2,c+16*b>>2);O.uniform4fv(P(a),d)},glUniformMatrix4fv:function(a,b,c,d){if(18>=b){var f=fb[16*b-1],g=G;d>>=2;for(var h=0;h<16*b;h+=16){var l=d+h;f[h]=g[l];f[h+1]=g[l+1];f[h+2]=g[l+2];f[h+3]=g[l+3];f[h+4]=g[l+4];f[h+5]=g[l+5];f[h+6]=g[l+6];f[h+7]=g[l+7];f[h+8]=g[l+8];f[h+9]=g[l+9];f[h+10]=g[l+10];f[h+11]=g[l+11];f[h+12]=g[l+12];f[h+13]=g[l+13];f[h+14]=g[l+14];f[h+15]=g[l+
15]}}else f=G.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(P(a),!!c,f)},glUseProgram:function(a){a=L[a];O.useProgram(a);O.C=a},glVertexAttribPointer:function(a,b,c,d,f,g){O.vertexAttribPointer(a,b,c,!!d,f,g)},glViewport:function(a,b,c,d){O.viewport(a,b,c,d)},glutCreateWindow:function(){e.g=Fb(e.canvas,!0,!0,{antialias:0!=(cc&128),depth:0!=(cc&16),stencil:0!=(cc&32),alpha:0!=(cc&8)});return e.g?1:0},glutDestroyWindow:function(){e.g=void 0;return 1},glutDisplayFunc:function(a){Tb=a},glutGet:function(a){switch(a){case 100:return 0;
case 101:return 0;case 102:return e.canvas.width;case 103:return e.canvas.height;case 200:return e.canvas.width;case 201:return e.canvas.height;case 500:return 0;case 501:return 0;case 502:return ac;case 503:return bc;case 700:return Date.now()-Vb;case 105:return e.g.getContextAttributes().stencil?8:0;case 106:return e.g.getContextAttributes().depth?8:0;case 110:return e.g.getContextAttributes().alpha?8:0;case 120:return e.g.getContextAttributes().antialias?1:0;default:throw"glutGet("+a+") not implemented yet";
}},glutGetModifiers:function(){return $b},glutIdleFunc:function(a){function b(){Wb&&(H.get(Wb)(),wb(b,4))}Wb||wb(b,0);Wb=a},glutInit:function(){Vb=Date.now();var a="ontouchstart"in document.documentElement;a&&(window.addEventListener("touchmove",Z,!0),window.addEventListener("touchstart",Z,!0),window.addEventListener("touchend",Z,!0));window.addEventListener("keydown",gc,!0);window.addEventListener("keyup",hc,!0);window.addEventListener("mousemove",ec,!0);window.addEventListener("mousedown",ic,!0);
window.addEventListener("mouseup",jc,!0);window.addEventListener("mousewheel",kc,!0);window.addEventListener("DOMMouseScroll",kc,!0);Qb.push(function(b,c){Zb&&H.get(Zb)(b,c)});Ba.push(function(){a&&(window.removeEventListener("touchmove",Z,!0),window.removeEventListener("touchstart",Z,!0),window.removeEventListener("touchend",Z,!0));window.removeEventListener("keydown",gc,!0);window.removeEventListener("keyup",hc,!0);window.removeEventListener("mousemove",ec,!0);window.removeEventListener("mousedown",
ic,!0);window.removeEventListener("mouseup",jc,!0);window.removeEventListener("mousewheel",kc,!0);window.removeEventListener("DOMMouseScroll",kc,!0);e.canvas.width=e.canvas.height=1})},glutInitDisplayMode:function(a){cc=a},glutInitWindowPosition:function(){},glutInitWindowSize:function(a,b){Rb(ac=a,bc=b)},glutKeyboardFunc:function(a){Xb=a},glutMainLoop:function(){var a=e.canvas.width,b=e.canvas.height;Jb();Rb(a,b,!0);Zb&&H.get(Zb)(a,b);Sb();Sb();throw"unwind";},glutMouseFunc:function(a){Y=a},glutPostRedisplay:Sb,
glutReshapeFunc:function(a){Zb=a},glutSpecialFunc:function(a){Yb=a},glutSwapBuffers:function(){},setTempRet0:function(){}};
(function(){function a(f){e.asm=f.exports;na=e.asm.memory;f=na.buffer;e.HEAP8=va=new Int8Array(f);e.HEAP16=new Int16Array(f);e.HEAP32=F=new Int32Array(f);e.HEAPU8=E=new Uint8Array(f);e.HEAPU16=wa=new Uint16Array(f);e.HEAPU32=xa=new Uint32Array(f);e.HEAPF32=G=new Float32Array(f);e.HEAPF64=new Float64Array(f);H=e.asm.__indirect_function_table;za.unshift(e.asm.__wasm_call_ctors);I--;e.monitorRunDependencies&&e.monitorRunDependencies(I);0==I&&(null!==Ea&&(clearInterval(Ea),Ea=null),J&&(f=J,J=null,f()))}
function b(f){a(f.instance)}function c(f){return Ia().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(f,function(g){z("failed to asynchronously prepare wasm: "+g);x(g)})}var d={env:nc,wasi_snapshot_preview1:nc};I++;e.monitorRunDependencies&&e.monitorRunDependencies(I);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return z("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return A||"function"!==typeof WebAssembly.instantiateStreaming||
Fa()||K.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){z("wasm streaming compile failed: "+g);z("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.__wasm_call_ctors).apply(null,arguments)};var db=e._malloc=function(){return(db=e._malloc=e.asm.malloc).apply(null,arguments)};
e._main=function(){return(e._main=e.asm.main).apply(null,arguments)};e.___errno_location=function(){return(e.___errno_location=e.asm.__errno_location).apply(null,arguments)};e.stackSave=function(){return(e.stackSave=e.asm.stackSave).apply(null,arguments)};e.stackRestore=function(){return(e.stackRestore=e.asm.stackRestore).apply(null,arguments)};var ua=e.stackAlloc=function(){return(ua=e.stackAlloc=e.asm.stackAlloc).apply(null,arguments)};
e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.dynCall_jiji).apply(null,arguments)};var pc;function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}J=function qc(){pc||rc();pc||(J=qc)};
function rc(a){function b(){if(!pc&&(pc=!0,e.calledRun=!0,!C)){Ja(za);Ja(Aa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(sc){var c=a,d=e._main;c=c||[];var f=c.length+1,g=ua(4*(f+1));F[g>>2]=ta(ba);for(var h=1;h<f;h++)F[(g>>2)+h]=ta(c[h-1]);F[(g>>2)+f]=0;try{var l=d(f,g);pb(l)}catch(m){Ka(m)}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),Ca.unshift(c);Ja(Ca)}}a=a||aa;if(!(0<I)){if(e.preRun)for("function"==typeof e.preRun&&
(e.preRun=[e.preRun]);e.preRun.length;)Da();Ja(ya);0<I||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=rc;function pb(a){oa=oa=a;if(!(noExitRuntime||0<ka)){if(e.onExit)e.onExit(a);C=!0}ca(a,new ja(a))}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var sc=!0;e.noInitialRun&&(sc=!1);rc();
