
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var k={},n;for(n in f)f.hasOwnProperty(n)&&(k[n]=f[n]);var aa=[],ba="./this.program";function ca(a,b){throw b;}var da="object"===typeof window,r="function"===typeof importScripts,ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,u="",fa,ha,ia,v,w;
if(ea)u=r?require("path").dirname(u)+"/":__dirname+"/",fa=function(a,b){v||(v=require("fs"));w||(w=require("path"));a=w.normalize(a);return v.readFileSync(a,b?null:"utf8")},ia=function(a){a=fa(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},ha=function(a,b,c){v||(v=require("fs"));w||(w=require("path"));a=w.normalize(a);v.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/")),aa=process.argv.slice(2),"undefined"!==typeof module&&
(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof ja))throw a;}),process.on("unhandledRejection",x),ca=function(a,b){if(noExitRuntime||0<ka)throw process.exitCode=a,b;process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(da||r)r?u=self.location.href:"undefined"!==typeof document&&document.currentScript&&(u=document.currentScript.src),u=0!==u.indexOf("blob:")?u.substr(0,u.lastIndexOf("/")+1):"",fa=function(a){var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},r&&(ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var y=f.print||console.log.bind(console),z=f.printErr||console.warn.bind(console);for(n in k)k.hasOwnProperty(n)&&(f[n]=k[n]);
k=null;f.arguments&&(aa=f.arguments);f.thisProgram&&(ba=f.thisProgram);f.quit&&(ca=f.quit);function la(a){ma||(ma={});ma[a]||(ma[a]=1,z(a))}var ma,A;f.wasmBinary&&(A=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&x("no native wasm support detected");var na,B=!1,oa;function assert(a,b){a||x("Assertion failed: "+b)}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&pa)return pa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?qa(E,a,b):""}
function ra(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ta(a){var b=sa(a)+1,c=ua(b);ra(a,va,c,b);return c}var va,E,wa,F,xa,G,H,ya=[],za=[],Aa=[],Ba=[],Ca=[],ka=0;function Da(){var a=f.preRun.shift();ya.unshift(a)}var I=0,Ea=null,J=null;f.preloadedImages={};f.preloadedAudios={};
function x(a){if(f.onAbort)f.onAbort(a);z(a);B=!0;oa=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Fa(){return K.startsWith("data:application/octet-stream;base64,")}var K;K="test_character.wasm";if(!Fa()){var Ga=K;K=f.locateFile?f.locateFile(Ga,u):u+Ga}function Ha(){var a=K;try{if(a==K&&A)return new Uint8Array(A);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}
function Ia(){if(!A&&(da||r)){if("function"===typeof fetch&&!K.startsWith("file://"))return fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Ha()});if(ha)return new Promise(function(a,b){ha(K,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ha()})}
function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.$a;"number"===typeof c?void 0===b.Oa?H.get(c)():H.get(c)(b.Oa):c(void 0===b.Oa?null:b.Oa)}}}function Ka(a){a instanceof ja||"unwind"==a||(z("exception thrown: "+a),ca(1,a))}var La=[null,[],[]];
function Ma(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,h){b.drawElementsInstancedANGLE(c,d,e,g,h)})}
function Na(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Oa(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Pa=1,Qa=[],L=[],Ra=[],Sa=[],M=[],N=[],Ta=[],Ua={};function O(a){Va||(Va=a)}
function Wa(a){for(var b=Pa++,c=a.length;c<b;c++)a[c]=null;return b}function Xa(a,b){a.Ua||(a.Ua=a.getContext,a.getContext=function(d,e){e=a.Ua(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Ya(c,b):0}function Ya(a,b){var c=Wa(Ta),d={kb:c,attributes:b,version:b.cb,Sa:a};a.canvas&&(a.canvas.gb=d);Ta[c]=d;("undefined"===typeof b.Za||b.Za)&&Za(d);return c}
function Za(a){a||(a=$a);if(!a.bb){a.bb=!0;var b=a.Sa;Ma(b);Na(b);Oa(b);b.ib=b.getExtension("EXT_disjoint_timer_query");b.nb=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var ab={},Va,$a;function bb(a,b,c,d){for(var e=0;e<a;e++){var g=P[c](),h=g&&Wa(d);g?(g.name=h,d[h]=g):O(1282);F[b+4*e>>2]=h}}
function cb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":O(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:O(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)F[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){O(1280);z("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:O(1280);z("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}F[b>>2]=c}else O(1281)}function eb(a){var b=sa(a)+1,c=fb(b);ra(a,E,c,b);return c}
function gb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Q(a){var b=P.Ya;if(b){var c=b.Na[a];"number"===typeof c&&(b.Na[a]=c=P.getUniformLocation(b,b.Wa[a]+(0<c?"["+c+"]":"")));return c}O(1282)}var hb=[];
function ib(a,b){jb=a;kb=b;if(S)if(lb||(lb=!0),0==a)T=function(){var d=Math.max(0,mb+b-nb())|0;setTimeout(U,d)};else if(1==a)T=function(){ob(U)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);r?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}T=function(){setImmediate(U)}}}var nb;nb=ea?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};
function pb(a){function b(){if(c<qb){if(!(noExitRuntime||0<ka))try{rb(oa)}catch(d){Ka(d)}return!1}return!0}assert(!S,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");S=a;var c=qb;lb=!1;U=function(){if(!B)if(0<sb.length){var d=Date.now(),e=sb.shift();e.$a(e.Oa);if(tb){var g=tb,h=0==g%1?g-1:Math.floor(g);tb=e.hb?h:(8*g+(h+.5))/9}y('main loop blocker "'+e.name+
'" took '+(Date.now()-d)+" ms");f.setStatus&&(d=f.statusMessage||"Please wait...",e=tb,g=ub.jb,e?e<g?f.setStatus(d+" ("+(g-e)+"/"+g+")"):f.setStatus(d):f.setStatus(""));b()&&setTimeout(U,0)}else b()&&(vb=vb+1|0,1==jb&&1<kb&&0!=vb%kb?T():(0==jb&&(mb=nb()),wb(a),b()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.eb&&SDL.audio.eb(),T())))}}function xb(a){if(!B)try{a()}catch(b){Ka(b)}}function yb(a,b){setTimeout(function(){xb(a)},b)}var lb=!1,T=null,qb=0,S=null,jb=0,kb=0,vb=0,sb=[];
function wb(a){B||f.preMainLoop&&!1===f.preMainLoop()||(xb(a),f.postMainLoop&&f.postMainLoop())}var ub={},mb,U,tb,zb=!1,Ab=!1,Bb=[];
function Cb(){function a(){Ab=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!Db){Db=!0;try{Eb=!0}catch(c){Eb=!1,y("warning: no blob constructor, cannot create blobs with mimetypes")}Fb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Eb?null:y("warning: no BlobBuilder");Gb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;f.Va||"undefined"!==typeof Gb||(y("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.Va=!0);f.preloadPlugins.push({canHandle:function(c){return!f.Va&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=null;if(Eb)try{h=new Blob([c],{type:Hb(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Hb(d)}))}catch(p){la("Blob constructor present but fails: "+
p+"; falling back to blob builder")}h||(h=new Fb,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var l=Gb.createObjectURL(h),m=new Image;m.onload=function(){assert(m.complete,"Image "+d+" could not be decoded");var p=document.createElement("canvas");p.width=m.width;p.height=m.height;p.getContext("2d").drawImage(m,0,0);f.preloadedImages[d]=p;Gb.revokeObjectURL(l);e&&e(c)};m.onerror=function(){y("Image "+l+" could not be decoded");g&&g()};m.src=l}});f.preloadPlugins.push({canHandle:function(c){return!f.ob&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,g){function h(q){m||(m=!0,f.preloadedAudios[d]=q,e&&e(c))}function l(){m||(m=!0,f.preloadedAudios[d]=new Audio,g&&g())}var m=!1;if(Eb){try{var p=new Blob([c],{type:Hb(d)})}catch(q){return l()}p=Gb.createObjectURL(p);var t=new Audio;t.addEventListener("canplaythrough",function(){h(t)},!1);t.onerror=function(){if(!m){y("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var q="",C=0,R=0,db=0;db<c.length;db++)for(C=
C<<8|c[db],R+=8;6<=R;){var qc=C>>R-6&63;R-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[qc]}2==R?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(C&3)<<4],q+="=="):4==R&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(C&15)<<2],q+="=");t.src="data:audio/x-"+d.substr(-3)+";base64,"+q;h(t)}};t.src=p;yb(function(){h(t)},1E4)}else return l()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&
b.addEventListener("click",function(c){!Ab&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Ib(a,b,c,d){if(b&&f.Ma&&a==f.canvas)return f.Ma;var e;if(b){var g={antialias:!1,alpha:!1,cb:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof ab&&(e=Xa(a,g)))var l=Ta[e].Sa}else l=a.getContext("2d");if(!l)return null;c&&(b||assert("undefined"===typeof P,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Ma=l,b&&($a=Ta[e],f.Ma=P=$a&&$a.Sa),f.pb=b,Bb.forEach(function(m){m()}),Cb());return l}var Jb=!1,Kb=void 0,V=void 0;
function Lb(a,b){function c(){zb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Mb,Kb&&d.requestPointerLock(),zb=!0,V?("undefined"!=typeof SDL&&(F[SDL.screen>>2]=xa[SDL.screen>>2]|8388608),Nb(f.canvas),Ob()):Nb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),V?("undefined"!=typeof SDL&&(F[SDL.screen>>2]=xa[SDL.screen>>2]&
-8388609),Nb(f.canvas),Ob()):Nb(d));if(f.onFullScreen)f.onFullScreen(zb);if(f.onFullscreen)f.onFullscreen(zb)}Kb=a;V=b;"undefined"===typeof Kb&&(Kb=!0);"undefined"===typeof V&&(V=!1);var d=f.canvas;Jb||(Jb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Mb(){if(!zb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Pb=0;function ob(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Pb)Pb=b+1E3/60;else for(;b+2>=Pb;)Pb+=1E3/60;setTimeout(a,Math.max(Pb-b,0))}}
function Hb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var W=0,X=0,Qb=0,Rb=0;
function Sb(a){if(Ab)"mousemove"!=a.type&&"mozMovementX"in a?Qb=Rb=0:(Qb=a.movementX||a.mozMovementX||a.webkitMovementX||0,Rb=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(W=SDL.lb+Qb,X=SDL.mb+Rb):(W+=Qb,X+=Rb);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==a.type&&
"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,Qb=e-W,Rb=a-X,W=e,X=a)}}var Tb=[];function Ob(){var a=f.canvas;Tb.forEach(function(b){b(a.width,a.height)})}function Ub(a,b,c){Nb(f.canvas,a,b);c||Ob()}
function Nb(a,b,c){b&&c?(a.fb=b,a.ab=c):(b=a.fb,c=a.ab);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}V?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Db,Eb,Fb,Gb;
function Vb(){Wb&&!Xb&&(Xb=!0,ob(function(){Xb=!1;wb(function(){H.get(Wb)()})}))}var Yb=null,Zb=null,Wb=null,$b=null,ac=null,bc=null,Y=null,cc=0,dc=256,ec=256,fc=18,Xb=!1;function gc(a){cc=0;a.shiftKey&&(cc+=1);a.ctrlKey&&(cc+=2);a.altKey&&(cc+=4)}function hc(a){Sb(a)}
function ic(a){if(a.ctrlKey||a.altKey||a.metaKey)return null;var b=a.keyCode;if(48<=b&&57>=b)return b;if(65<=b&&90>=b)return a.shiftKey?b:b+32;if(96<=b&&105>=b)return b-48;if(106<=b&&111>=b)return b-106+42;switch(b){case 9:case 13:case 27:case 32:case 61:return b}a=a.shiftKey;switch(b){case 186:return a?58:59;case 187:return a?43:61;case 188:return a?60:44;case 189:return a?95:45;case 190:return a?62:46;case 191:return a?63:47;case 219:return a?123:91;case 220:return a?124:47;case 221:return a?125:
93;case 222:return a?34:39}return null}
function jc(a){if(ac||$b){var b=null;switch(a.keyCode){case 8:b=120;break;case 46:b=111;break;case 112:b=1;break;case 113:b=2;break;case 114:b=3;break;case 115:b=4;break;case 116:b=5;break;case 117:b=6;break;case 118:b=7;break;case 119:b=8;break;case 120:b=9;break;case 121:b=10;break;case 122:b=11;break;case 123:b=12;break;case 37:b=100;break;case 38:b=101;break;case 39:b=102;break;case 40:b=103;break;case 33:b=104;break;case 34:b=105;break;case 36:b=106;break;case 35:b=107;break;case 45:b=108;break;
case 16:case 5:b=112;break;case 6:b=113;break;case 17:case 3:b=114;break;case 4:b=115;break;case 18:case 2:b=116;break;case 1:b=117}null!==b?ac&&(a.preventDefault(),gc(a),H.get(ac)(b,W,X)):(b=ic(a),null!==b&&$b&&(a.preventDefault(),gc(a),H.get($b)(b,W,X)))}}function kc(){}
function Z(a){if(a.target==f.canvas){var b=a.changedTouches[0];switch(a.type){case "touchstart":var c="mousedown";break;case "touchmove":c="mousemove";break;case "touchend":c="mouseup";break;default:return}var d=document.createEvent("MouseEvent");d.initMouseEvent(c,!0,!0,window,1,b.screenX,b.screenY,b.clientX,b.clientY,!1,!1,!1,!1,0,null);b.target.dispatchEvent(d);a.preventDefault()}}
function lc(a){Sb(a);if(a.target==f.canvas&&Y){try{a.target.setCapture()}catch(b){}a.preventDefault();gc(a);H.get(Y)(a.button,0,W,X)}}function mc(a){Sb(a);Y&&(a.preventDefault(),gc(a),H.get(Y)(a.button,1,W,X))}
function nc(a){Sb(a);switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);var c=3;0>b&&(c=4);Y&&(a.preventDefault(),gc(a),H.get(Y)(c,0,W,X))}
for(var P,oc=new Float32Array(288),pc=0;288>pc;++pc)hb[pc]=oc.subarray(0,pc+1);f.requestFullscreen=function(a,b){Lb(a,b)};f.requestAnimationFrame=function(a){ob(a)};f.setCanvasSize=function(a,b,c){Ub(a,b,c)};f.pauseMainLoop=function(){T=null;qb++};f.resumeMainLoop=function(){qb++;var a=jb,b=kb,c=S;S=null;pb(c);ib(a,b);T()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
f.createContext=function(a,b,c,d){return Ib(a,b,c,d)};
var rc={a:function(a,b,c,d){x("Assertion failed: "+D(a)+", at: "+[b?D(b):"unknown filename",c,d?D(d):"unknown function"])},fa:function(a,b,c){E.copyWithin(a,b,b+c)},ga:function(){x("OOM")},F:function(a){rb(a)},ha:function(){return 0},ea:function(){},R:function(a,b,c,d){for(var e=0,g=0;g<c;g++){for(var h=F[b+8*g>>2],l=F[b+(8*g+4)>>2],m=0;m<l;m++){var p=E[h+m],t=La[a];0===p||10===p?((1===a?y:z)(qa(t,0)),t.length=0):t.push(p)}e+=l}F[d>>2]=e;return 0},Ba:function(a){P.activeTexture(a)},C:function(a,b){P.attachShader(L[a],
N[b])},d:function(a,b){P.bindBuffer(a,Qa[b])},p:function(a,b){P.bindFramebuffer(a,Ra[b])},Ca:function(a,b){P.bindRenderbuffer(a,Sa[b])},t:function(a,b){P.bindTexture(a,M[b])},ya:function(a,b){P.blendFunc(a,b)},r:function(a,b,c,d){P.bufferData(a,c?E.subarray(c,c+b):b,d)},o:function(a,b,c,d){P.bufferSubData(a,b,E.subarray(d,d+c))},S:function(a){return P.checkFramebufferStatus(a)},Z:function(a){P.clear(a)},xa:function(a,b,c,d){P.clearColor(a,b,c,d)},ba:function(a,b,c,d){P.colorMask(!!a,!!b,!!c,!!d)},
K:function(a){P.compileShader(N[a])},Y:function(){var a=Wa(L),b=P.createProgram();b.name=a;b.Ra=b.Pa=b.Qa=0;b.Ta=1;L[a]=b;return a},M:function(a){var b=Wa(N);N[b]=P.createShader(a);return b},aa:function(a){P.cullFace(a)},n:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],e=Qa[d];e&&(P.deleteBuffer(e),e.name=0,Qa[d]=null)}},z:function(a){if(a){var b=L[a];b?(P.deleteProgram(b),b.name=0,L[a]=null):O(1281)}},u:function(a){if(a){var b=N[a];b?(P.deleteShader(b),N[a]=null):O(1281)}},O:function(a,b){for(var c=
0;c<a;c++){var d=F[b+4*c>>2],e=M[d];e&&(P.deleteTexture(e),e.name=0,M[d]=null)}},x:function(a){P.depthMask(!!a)},q:function(a){P.disable(a)},h:function(a){P.disableVertexAttribArray(a)},Fa:function(a,b,c){P.drawArrays(a,b,c)},e:function(a,b,c,d){P.drawElements(a,b,c,d)},k:function(a){P.enable(a)},i:function(a){P.enableVertexAttribArray(a)},ra:function(a,b,c,d){P.framebufferRenderbuffer(a,b,c,Sa[d])},V:function(a,b,c,d,e){P.framebufferTexture2D(a,b,c,M[d],e)},D:function(a){P.frontFace(a)},v:function(a,
b){bb(a,b,"createBuffer",Qa)},da:function(a,b){bb(a,b,"createFramebuffer",Ra)},Ea:function(a,b){bb(a,b,"createRenderbuffer",Sa)},P:function(a,b){bb(a,b,"createTexture",M)},G:function(a,b){return P.getAttribLocation(L[a],D(b))},Da:function(a,b){cb(a,b)},W:function(a,b,c,d){a=P.getProgramInfoLog(L[a]);null===a&&(a="(unknown error)");b=0<b&&d?ra(a,E,d,b):0;c&&(F[c>>2]=b)},B:function(a,b,c){if(c)if(a>=Pa)O(1281);else if(a=L[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),F[c>>2]=
a.length+1;else if(35719==b){if(!a.Ra)for(b=0;b<P.getProgramParameter(a,35718);++b)a.Ra=Math.max(a.Ra,P.getActiveUniform(a,b).name.length+1);F[c>>2]=a.Ra}else if(35722==b){if(!a.Pa)for(b=0;b<P.getProgramParameter(a,35721);++b)a.Pa=Math.max(a.Pa,P.getActiveAttrib(a,b).name.length+1);F[c>>2]=a.Pa}else if(35381==b){if(!a.Qa)for(b=0;b<P.getProgramParameter(a,35382);++b)a.Qa=Math.max(a.Qa,P.getActiveUniformBlockName(a,b).length+1);F[c>>2]=a.Qa}else F[c>>2]=P.getProgramParameter(a,b);else O(1281)},J:function(a,
b,c,d){a=P.getShaderInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?ra(a,E,d,b):0;c&&(F[c>>2]=b)},w:function(a,b,c){c?35716==b?(a=P.getShaderInfoLog(N[a]),null===a&&(a="(unknown error)"),F[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(N[a]),F[c>>2]=a?a.length+1:0):F[c>>2]=P.getShaderParameter(N[a],b):O(1281)},A:function(a){var b=Ua[a];if(!b){switch(a){case 7939:b=P.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=eb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
P.getParameter(a))||O(1280);b=b&&eb(b);break;case 7938:b=eb("OpenGL ES 2.0 ("+P.getParameter(7938)+")");break;case 35724:b=P.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=eb(b);break;default:O(1280)}Ua[a]=b}return b},f:function(a,b){b=D(b);if(a=L[a]){var c=a,d=c.Na,e=c.Xa,g;if(!d)for(c.Na=d={},c.Wa={},g=0;g<P.getProgramParameter(c,35718);++g){var h=P.getActiveUniform(c,g);var l=h.name;
h=h.size;var m=gb(l);m=0<m?l.slice(0,m):l;var p=c.Ta;c.Ta+=h;e[m]=[h,p];for(l=0;l<h;++l)d[p]=l,c.Wa[p++]=m}c=a.Na;d=0;e=b;g=gb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Xa[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else O(1281);return-1},I:function(a){P.lineWidth(a)},X:function(a){a=L[a];P.linkProgram(a);a.Na=0;a.Xa={}},_:function(a,b){P.polygonOffset(a,b)},za:function(a,b,c,d){P.renderbufferStorage(a,b,c,d)},L:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=
d?F[d+4*g>>2]:-1;e+=D(F[c+4*g>>2],0>h?void 0:h)}P.shaderSource(N[a],e)},ca:function(a,b,c,d,e,g,h,l,m){var p=P,t=p.texImage2D;if(m){var q=l-5120;q=1==q?E:4==q?F:6==q?G:5==q||28922==q?xa:wa;var C=31-Math.clz32(q.BYTES_PER_ELEMENT);m=q.subarray(m>>C,m+e*(d*({5:3,6:4,8:2,29502:3,29504:4}[h-6402]||1)*(1<<C)+4-1&-4)>>C)}else m=null;t.call(p,a,b,c,d,e,g,h,l,m)},Q:function(a,b,c){P.texParameterf(a,b,c)},y:function(a,b,c){P.texParameteri(a,b,c)},$:function(a,b){P.uniform1f(Q(a),b)},N:function(a,b){P.uniform1i(Q(a),
b)},E:function(a,b,c){P.uniform2f(Q(a),b,c)},s:function(a,b,c,d){P.uniform3f(Q(a),b,c,d)},Aa:function(a,b,c){if(96>=b)for(var d=hb[3*b-1],e=0;e<3*b;e+=3)d[e]=G[c+4*e>>2],d[e+1]=G[c+(4*e+4)>>2],d[e+2]=G[c+(4*e+8)>>2];else d=G.subarray(c>>2,c+12*b>>2);P.uniform3fv(Q(a),d)},b:function(a,b,c,d,e){P.uniform4f(Q(a),b,c,d,e)},g:function(a,b,c){if(72>=b){var d=hb[4*b-1],e=G;c>>=2;for(var g=0;g<4*b;g+=4){var h=c+g;d[g]=e[h];d[g+1]=e[h+1];d[g+2]=e[h+2];d[g+3]=e[h+3]}}else d=G.subarray(c>>2,c+16*b>>2);P.uniform4fv(Q(a),
d)},l:function(a,b,c,d){if(18>=b){var e=hb[16*b-1],g=G;d>>=2;for(var h=0;h<16*b;h+=16){var l=d+h;e[h]=g[l];e[h+1]=g[l+1];e[h+2]=g[l+2];e[h+3]=g[l+3];e[h+4]=g[l+4];e[h+5]=g[l+5];e[h+6]=g[l+6];e[h+7]=g[l+7];e[h+8]=g[l+8];e[h+9]=g[l+9];e[h+10]=g[l+10];e[h+11]=g[l+11];e[h+12]=g[l+12];e[h+13]=g[l+13];e[h+14]=g[l+14];e[h+15]=g[l+15]}}else e=G.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(Q(a),!!c,e)},c:function(a){a=L[a];P.useProgram(a);P.Ya=a},j:function(a,b,c,d,e,g){P.vertexAttribPointer(a,b,c,!!d,e,g)},
m:function(a,b,c,d){P.viewport(a,b,c,d)},qa:function(){f.Ma=Ib(f.canvas,!0,!0,{antialias:0!=(fc&128),depth:0!=(fc&16),stencil:0!=(fc&32),alpha:0!=(fc&8)});return f.Ma?1:0},ua:function(){f.Ma=void 0;return 1},T:function(a){Wb=a},U:function(a){switch(a){case 100:return 0;case 101:return 0;case 102:return f.canvas.width;case 103:return f.canvas.height;case 200:return f.canvas.width;case 201:return f.canvas.height;case 500:return 0;case 501:return 0;case 502:return dc;case 503:return ec;case 700:return Date.now()-
Yb;case 105:return f.Ma.getContextAttributes().stencil?8:0;case 106:return f.Ma.getContextAttributes().depth?8:0;case 110:return f.Ma.getContextAttributes().alpha?8:0;case 120:return f.Ma.getContextAttributes().antialias?1:0;default:throw"glutGet("+a+") not implemented yet";}},H:function(){return cc},ma:function(a){function b(){Zb&&(H.get(Zb)(),yb(b,4))}Zb||yb(b,0);Zb=a},wa:function(){Yb=Date.now();var a="ontouchstart"in document.documentElement;a&&(window.addEventListener("touchmove",Z,!0),window.addEventListener("touchstart",
Z,!0),window.addEventListener("touchend",Z,!0));window.addEventListener("keydown",jc,!0);window.addEventListener("keyup",kc,!0);window.addEventListener("mousemove",hc,!0);window.addEventListener("mousedown",lc,!0);window.addEventListener("mouseup",mc,!0);window.addEventListener("mousewheel",nc,!0);window.addEventListener("DOMMouseScroll",nc,!0);Tb.push(function(b,c){bc&&H.get(bc)(b,c)});Ba.push(function(){a&&(window.removeEventListener("touchmove",Z,!0),window.removeEventListener("touchstart",Z,!0),
window.removeEventListener("touchend",Z,!0));window.removeEventListener("keydown",jc,!0);window.removeEventListener("keyup",kc,!0);window.removeEventListener("mousemove",hc,!0);window.removeEventListener("mousedown",lc,!0);window.removeEventListener("mouseup",mc,!0);window.removeEventListener("mousewheel",nc,!0);window.removeEventListener("DOMMouseScroll",nc,!0);f.canvas.width=f.canvas.height=1})},va:function(a){fc=a},ta:function(){},sa:function(a,b){Ub(dc=a,ec=b)},pa:function(a){$b=a},ka:function(){var a=
f.canvas.width,b=f.canvas.height;Mb();Ub(a,b,!0);bc&&H.get(bc)(a,b);Vb();Vb();throw"unwind";},na:function(a){Y=a},ja:Vb,la:function(a){bc=a},oa:function(a){ac=a},ia:function(){}};
(function(){function a(e){f.asm=e.exports;na=f.asm.Ga;e=na.buffer;f.HEAP8=va=new Int8Array(e);f.HEAP16=new Int16Array(e);f.HEAP32=F=new Int32Array(e);f.HEAPU8=E=new Uint8Array(e);f.HEAPU16=wa=new Uint16Array(e);f.HEAPU32=xa=new Uint32Array(e);f.HEAPF32=G=new Float32Array(e);f.HEAPF64=new Float64Array(e);H=f.asm.Ka;za.unshift(f.asm.Ha);I--;f.monitorRunDependencies&&f.monitorRunDependencies(I);0==I&&(null!==Ea&&(clearInterval(Ea),Ea=null),J&&(e=J,J=null,e()))}function b(e){a(e.instance)}function c(e){return Ia().then(function(g){return WebAssembly.instantiate(g,
d)}).then(function(g){return g}).then(e,function(g){z("failed to asynchronously prepare wasm: "+g);x(g)})}var d={a:rc};I++;f.monitorRunDependencies&&f.monitorRunDependencies(I);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return z("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return A||"function"!==typeof WebAssembly.instantiateStreaming||Fa()||K.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(g){z("wasm streaming compile failed: "+g);z("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.Ha).apply(null,arguments)};var fb=f._malloc=function(){return(fb=f._malloc=f.asm.Ia).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Ja).apply(null,arguments)};var ua=f.stackAlloc=function(){return(ua=f.stackAlloc=f.asm.La).apply(null,arguments)},sc;
function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}J=function tc(){sc||uc();sc||(J=tc)};
function uc(a){function b(){if(!sc&&(sc=!0,f.calledRun=!0,!B)){Ja(za);Ja(Aa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(vc){var c=a,d=f._main;c=c||[];var e=c.length+1,g=ua(4*(e+1));F[g>>2]=ta(ba);for(var h=1;h<e;h++)F[(g>>2)+h]=ta(c[h-1]);F[(g>>2)+e]=0;try{var l=d(e,g);rb(l)}catch(m){Ka(m)}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Ca.unshift(c);Ja(Ca)}}a=a||aa;if(!(0<I)){if(f.preRun)for("function"==typeof f.preRun&&
(f.preRun=[f.preRun]);f.preRun.length;)Da();Ja(ya);0<I||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=uc;function rb(a){oa=oa=a;if(!(noExitRuntime||0<ka)){if(f.onExit)f.onExit(a);B=!0}ca(a,new ja(a))}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var vc=!0;f.noInitialRun&&(vc=!1);uc();
